name: "Bug report"
description: 提交问题 Report bug
title: ""
labels: [Bug]
body:
  - type: checkboxes
    attributes:
      label: **检查整合包版本 Check if modpack version is newest**
      options:
        - label: "确认整合包版本是否为最新，看标题界面右下角两行小字，红框圈住位置会有 v0.x.x.x 形式的整合包版本。最新整合包版本可通过三个小人下方的公告确认。如果不是最新，请先更新到最新以避免反馈已修复的bug。如果是最新，请填写你的整合包版本。"
          required: true
  - type: input
      attributes:
        label: 整合包版本
        placeholder: ""
        validations:
          required: true
        
